CREATE TABLE PLAYER (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(45) NOT NULL
);

CREATE TABLE chartscounted(
  player INT NOT NULL,
  chartsCounted INT NOT NULL,
  trials INT NULL,
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT);
